### ISSUE TITLE
Server Deployement: issues when installing using snap on ubuntu 16.04

### ISSUE THREAD

**Issue by rahmanih** [thinger-io/Docs#10]
Hi,
I followed the documentation to install the thinger.io server on my Ubuntu machine but I'm getting the following error:

> error: cannot install "thinger-maker-server": Get
>        https://search.apps.ubuntu.com/api/v1/snaps/details/core?channel=stable&fields=anon_download_url%2Carchitecture%2Cchannel%2Cdownload_sha3_384%2Csummary%2Cdescription%2Cdeltas%2Cbinary_filesize%2Cdownload_url%2Cepoch%2Cicon_url%2Clast_updated%2Cpackage_name%2Cprices%2Cpublisher%2Cratings_average%2Crevision%2Cscreenshot_urls%2Csnap_id%2Csupport_url%2Ccontact%2Ctitle%2Ccontent%2Cversion%2Corigin%2Cdeveloper_id%2Cprivate%2Cconfinement%2Cchannel_maps_list:
>        x509: certificate signed by unknown authority

is there any way to fix that?

regards
Haithem.

**Comment by antonprafanto** [comment]
hello, i had same problem :(

**Comment by alvarolb** [comment]
The problem seems to be related with the snap system and certificates, not a thinger issue. Is your ubuntu a fresh install? What version?

**Comment by rahmanih** [comment]
switched  to  fedora  26  it works  perfectly

`[rahmanih@OroJackson ~]$    snap find thinger`
`Name                  Version  Developer  Notes  Summary`
`thinger-maker-server  1.3.0    thinger    -      Thinger.io Internet Of Things Server`

from my side   you can close this bug
regards
