### ISSUE TITLE
Raspberry Pi wiringPi issue

### ISSUE THREAD

**Issue by abhinuvpitale** [thinger-io/Docs#16]
I was working on integrating the wiringPi library with thinger.io app (using the linux documentation which specifies that it is using the raspberrypi as the platform)
The run.sh script in the linux example needs to have 
`cmake -DCMAKE_BUILD_TYPE=Release -DDAEMON=OFF -DRASPBERRY=ON`
 instead of the current 
`cmake -DCMAKE_BUILD_TYPE=Release -DDAEMON=OFF`

I guess this needs to be changed in the documentation as well as the linux example package

**Comment by alvarolb** [comment]
Hi! Can you submit a pull request? thanks!!

**Comment by abhinuvpitale** [comment]
@alvarolb  check?
